/**
 * The invoice pipeline over HTTP: upload, parse, normalise, detect duplicates,
 * store, and refresh the forecasting dataset.
 *
 * These tests push real PDFs through the real Python extractor. Stubbing the
 * parser would leave the most failure-prone stage of the system untested -- the
 * interesting bugs live in what pdfplumber returns for an awkward document, not
 * in the code that reads a mocked result.
 *
 * Fixtures are generated by scripts/make_test_invoice.py, which already builds
 * the cases that matter: a corrected invoice colliding with a stored order
 * number, a multi-item order, a scan with no text layer, an unreadable date.
 */

import { beforeAll, describe, expect, it } from "vitest";

import { asAdmin, asEmployee } from "../helpers/client.js";
import { FIXTURES, NOT_A_PDF, bundledInvoice, bundledInvoiceNames, generatedInvoice, generatedFixtureDir } from "../helpers/fixtures.js";
import { pythonAvailable, useDataSandbox } from "../helpers/sandbox.js";

const runnable = pythonAvailable();
const describeWithPython = runnable ? describe : describe.skip;

if (!runnable) {
  console.warn("Invoice pipeline suite skipped: Python toolchain unavailable.");
}

/** Uploads one or more buffers to the import endpoint. */
const upload = (files) => {
  const request = asAdmin().post("/admin/invoices/import");
  for (const [name, buffer] of files) request.attach("invoices", buffer, name);
  return request;
};

const outcomesOf = (body) => body.files.map((file) => file.outcome);

describeWithPython("POST /admin/invoices/import", () => {
  useDataSandbox();

  beforeAll(() => {
    // Build the fixtures once, and fail loudly here rather than inside a test.
    generatedFixtureDir();
  });

  it("imports a genuine SmartQ invoice", async () => {
    const name = bundledInvoiceNames()[0];
    const response = await upload([[name, bundledInvoice(name)]]);

    expect(response.status).toBe(201);
    expect(response.body.summary.imported).toBe(1);
  });

  it("extracts the fields the dataset is built from", async () => {
    const name = bundledInvoiceNames()[0];
    await upload([[name, bundledInvoice(name)]]);

    const [record] = (await asAdmin().get("/admin/invoices/records")).body.records;
    expect(record).toMatchObject({
      orderId: expect.any(String),
      orderDate: expect.stringMatching(/^\d{4}-\d{2}-\d{2}$/),
      cafeteria: expect.any(String),
      vendor: expect.any(String),
      items: expect.any(Array),
    });
    expect(record.items.length).toBeGreaterThan(0);
  });

  it("reads every line item off a multi-item order", async () => {
    await upload([[FIXTURES.multiItem, generatedInvoice(FIXTURES.multiItem)]]);

    const { records } = (await asAdmin().get("/admin/invoices/records")).body;
    expect(records[0].items.length).toBeGreaterThan(1);
    expect(records[0].totalQuantity).toBeGreaterThan(1);
  });

  it("imports a whole batch in one request", async () => {
    const names = bundledInvoiceNames().slice(0, 3);
    const response = await upload(names.map((name) => [name, bundledInvoice(name)]));

    expect(response.body.summary.received).toBe(names.length);
    expect(response.body.summary.imported + response.body.summary.duplicates).toBe(names.length);
  });

  it("does not let one bad file abort the rest of the batch", async () => {
    const name = bundledInvoiceNames()[0];
    const response = await upload([
      ["broken.pdf", NOT_A_PDF],
      [name, bundledInvoice(name)],
    ]);

    expect(response.body.summary.rejected).toBe(1);
    expect(response.body.summary.imported).toBe(1);
  });

  it("reports the stage each file reached", async () => {
    const name = bundledInvoiceNames()[0];
    const response = await upload([[name, bundledInvoice(name)]]);

    expect(response.body.files[0].stage).toBe("database");
  });

  it("requires at least one attachment", async () => {
    const response = await asAdmin().post("/admin/invoices/import");

    expect(response.status).toBe(400);
    expect(response.body.error).toMatch(/attach at least one PDF/i);
  });

  describe("rejections", () => {
    it("refuses a file that is not a PDF, whatever it is named", async () => {
      const response = await upload([["invoice.pdf", NOT_A_PDF]]);

      expect(response.body.files[0]).toMatchObject({ outcome: "rejected", stage: "validation", code: "NOT_A_PDF" });
    });

    it("refuses an empty file", async () => {
      const response = await upload([["empty.pdf", Buffer.from("")]]);
      expect(response.body.summary.rejected).toBe(1);
    });

    it("refuses a scan with no text layer, and says why", async () => {
      const response = await upload([[FIXTURES.scannedNoText, generatedInvoice(FIXTURES.scannedNoText)]]);
      const [file] = response.body.files;

      expect(file.outcome).toBe("rejected");
      expect(file.message).toMatch(/text|scan|invoice/i);
    });

    it("refuses a PDF that is simply not an invoice", async () => {
      const response = await upload([[FIXTURES.notAnInvoice, generatedInvoice(FIXTURES.notAnInvoice)]]);
      expect(response.body.files[0].outcome).toBe("rejected");
    });

    it("refuses an invoice whose date cannot be interpreted", async () => {
      const response = await upload([[FIXTURES.badDate, generatedInvoice(FIXTURES.badDate)]]);
      const [file] = response.body.files;

      expect(file.outcome).toBe("rejected");
      expect(["BAD_DATE", "MISSING_ORDER_DATE", "NOT_SMARTQ_INVOICE"]).toContain(file.code);
    });

    it("stores nothing that was rejected", async () => {
      await upload([["broken.pdf", NOT_A_PDF]]);
      expect((await asAdmin().get("/admin/invoices/records")).body.total).toBe(0);
    });

    it("sanitises a traversal attempt in the uploaded filename", async () => {
      const name = bundledInvoiceNames()[0];
      const response = await upload([["../../../../etc/passwd.pdf", bundledInvoice(name)]]);

      expect(response.body.files[0].fileName).toBe("passwd.pdf");
      expect(response.body.files[0].fileName).not.toMatch(/[\\/]/);
    });
  });

  describe("duplicate detection", () => {
    const importOriginal = async () => {
      const name = bundledInvoiceNames()[0];
      await upload([[name, bundledInvoice(name)]]);
      return name;
    };

    it("treats the same file uploaded twice as a duplicate", async () => {
      const name = await importOriginal();
      const response = await upload([[name, bundledInvoice(name)]]);

      expect(response.body.summary.duplicates).toBe(1);
      expect(response.body.files[0].reason).toBe("identical-file");
    });

    it("detects a duplicate by content, so renaming the file changes nothing", async () => {
      const name = await importOriginal();
      const response = await upload([["totally-different-name.pdf", bundledInvoice(name)]]);

      expect(response.body.summary.duplicates).toBe(1);
    });

    it("detects duplicates inside a single batch", async () => {
      const name = bundledInvoiceNames()[0];
      const response = await upload([
        [name, bundledInvoice(name)],
        ["copy.pdf", bundledInvoice(name)],
      ]);

      expect(response.body.summary.imported).toBe(1);
      expect(response.body.summary.duplicates).toBe(1);
    });

    it("stores one record no matter how many times the file arrives", async () => {
      const name = await importOriginal();
      await upload([[name, bundledInvoice(name)]]);
      await upload([[name, bundledInvoice(name)]]);

      expect((await asAdmin().get("/admin/invoices/records")).body.total).toBe(1);
    });
  });

  describe("conflicts", () => {
    /** Imports the bundled invoice, then a corrected version of the same order. */
    const raiseConflict = async () => {
      await upload([["invoice_G1004987.pdf", bundledInvoice("invoice_G1004987.pdf")]]);
      return upload([[FIXTURES.conflict, generatedInvoice(FIXTURES.conflict)]]);
    };

    it("parks a same-order-different-values invoice instead of applying it", async () => {
      const response = await raiseConflict();

      expect(response.body.summary.conflicts).toBe(1);
      expect(response.body.summary.imported).toBe(0);
      expect(outcomesOf(response.body)).toEqual(["conflict"]);
    });

    it("names the fields that disagree", async () => {
      const response = await raiseConflict();
      expect(response.body.files[0].changes.length).toBeGreaterThan(0);
    });

    it("leaves the stored record untouched while the conflict is open", async () => {
      await raiseConflict();
      const before = (await asAdmin().get("/admin/invoices/records")).body.records[0];

      const { conflicts } = (await asAdmin().get("/admin/invoices/conflicts")).body;
      expect(conflicts).toHaveLength(1);
      expect((await asAdmin().get("/admin/invoices/records")).body.records[0].totalAmount).toBe(before.totalAmount);
    });

    it("applies the correction only when an administrator accepts it", async () => {
      const raised = await raiseConflict();
      const conflictId = raised.body.files[0].conflictId;
      const original = (await asAdmin().get("/admin/invoices/records")).body.records[0].totalAmount;

      const resolved = await asAdmin().post(`/admin/invoices/conflicts/${conflictId}/resolve`).send({ action: "accept-incoming" });

      expect(resolved.status).toBe(200);
      expect((await asAdmin().get("/admin/invoices/records")).body.records[0].totalAmount).not.toBe(original);
    });

    it("keeps the stored figures when an administrator rejects the correction", async () => {
      const raised = await raiseConflict();
      const conflictId = raised.body.files[0].conflictId;
      const original = (await asAdmin().get("/admin/invoices/records")).body.records[0].totalAmount;

      await asAdmin().post(`/admin/invoices/conflicts/${conflictId}/resolve`).send({ action: "keep-existing" });

      expect((await asAdmin().get("/admin/invoices/records")).body.records[0].totalAmount).toBe(original);
    });

    it("refuses an unrecognised resolution action", async () => {
      const raised = await raiseConflict();
      const conflictId = raised.body.files[0].conflictId;

      const response = await asAdmin().post(`/admin/invoices/conflicts/${conflictId}/resolve`).send({ action: "rm -rf" });
      expect(response.status).toBe(400);
    });

    it("refuses to resolve a conflict that does not exist", async () => {
      const response = await asAdmin().post("/admin/invoices/conflicts/nope/resolve").send({ action: "keep-existing" });
      expect(response.status).toBe(400);
    });

    it("records the decision in the audit trail", async () => {
      const raised = await raiseConflict();
      await asAdmin()
        .post(`/admin/invoices/conflicts/${raised.body.files[0].conflictId}/resolve`)
        .send({ action: "keep-existing" });

      const { entries } = (await asAdmin().get("/admin/invoices/audit")).body;
      expect(entries.length).toBeGreaterThan(0);
    });
  });

  describe("the forecasting dataset", () => {
    it("refreshes when new invoices land", async () => {
      const name = bundledInvoiceNames()[0];
      const response = await upload([[name, bundledInvoice(name)]]);

      expect(response.body.dataset).not.toBeNull();
      expect(response.body.dataset.rows).toBeGreaterThan(0);
    });

    it("does not refresh when nothing was imported", async () => {
      const response = await upload([["broken.pdf", NOT_A_PDF]]);
      expect(response.body.dataset).toBeNull();
    });

    it("describes itself to the dashboard", async () => {
      const name = bundledInvoiceNames()[0];
      await upload([[name, bundledInvoice(name)]]);

      const response = await asAdmin().get("/admin/invoices/dataset");
      expect(response.status).toBe(200);
    });

    it("downloads as CSV once it has been generated", async () => {
      const name = bundledInvoiceNames()[0];
      await upload([[name, bundledInvoice(name)]]);

      const response = await asAdmin().get("/admin/invoices/dataset/download");
      expect(response.status).toBe(200);
      expect(response.headers["content-type"]).toMatch(/text\/csv/);
      expect(response.headers["content-disposition"]).toMatch(/attachment/);
    });

    it("says plainly that no dataset exists rather than serving an empty file", async () => {
      const response = await asAdmin().get("/admin/invoices/dataset/download");

      expect(response.status).toBe(404);
      expect(response.body.error).toMatch(/no dataset/i);
    });
  });

  describe("the vault of original PDFs", () => {
    it("serves an imported original back to an administrator", async () => {
      const name = bundledInvoiceNames()[0];
      const response = await upload([[name, bundledInvoice(name)]]);
      const hash = response.body.files[0].contentHash;

      const raw = await asAdmin().get(`/admin/invoices/raw/${hash}`);
      expect(raw.status).toBe(200);
      expect(raw.headers["content-type"]).toMatch(/application\/pdf/);
    });

    it("returns the original bytes unmodified", async () => {
      const name = bundledInvoiceNames()[0];
      const original = bundledInvoice(name);
      const response = await upload([[name, original]]);

      const raw = await asAdmin().get(`/admin/invoices/raw/${response.body.files[0].contentHash}`);
      expect(Buffer.from(raw.body)).toEqual(original);
    });

    it("refuses a hash that is not 64 hex characters", async () => {
      for (const hash of ["..", "not-a-hash", "a".repeat(63), `${"a".repeat(64)}x`]) {
        expect((await asAdmin().get(`/admin/invoices/raw/${hash}`)).status).toBe(404);
      }
    });

    it("refuses a traversal attempt dressed as a hash", async () => {
      const response = await asAdmin().get("/admin/invoices/raw/..%2f..%2f..%2finvoices.json");
      expect(response.status).toBe(404);
    });
  });
});

describeWithPython("POST /admin/invoices/scan", () => {
  const sandbox = useDataSandbox();

  it("says so when there is no drop folder on the server", async () => {
    const response = await asAdmin().post("/admin/invoices/scan");

    expect(response.status).toBe(404);
    expect(response.body.error).toMatch(/drop folder/i);
  });

  it("ingests the PDFs it finds in the drop folder", async () => {
    const fs = await import("node:fs");
    const path = await import("node:path");
    const folder = path.join(sandbox.dir, "invoices");
    fs.mkdirSync(folder, { recursive: true });

    const name = bundledInvoiceNames()[0];
    fs.writeFileSync(path.join(folder, name), bundledInvoice(name));

    const response = await asAdmin().post("/admin/invoices/scan");
    expect(response.status).toBe(201);
    expect(response.body.summary.imported).toBe(1);
  });

  it("reports an empty drop folder rather than an empty success", async () => {
    const fs = await import("node:fs");
    const path = await import("node:path");
    fs.mkdirSync(path.join(sandbox.dir, "invoices"), { recursive: true });

    const response = await asAdmin().post("/admin/invoices/scan");
    expect(response.status).toBe(400);
  });
});

describe("invoice endpoints an employee must never reach", () => {
  useDataSandbox();

  it("refuses an upload from an unauthenticated caller", async () => {
    const response = await asEmployee().post("/admin/invoices/import").attach("invoices", NOT_A_PDF, "invoice.pdf");
    expect(response.status).toBe(403);
  });

  it("refuses to list stored invoices", async () => {
    expect((await asEmployee().get("/admin/invoices/records")).status).toBe(403);
  });

  it("carries no employee identifier in a stored record, by construction", async () => {
    // Invoices describe purchases, not people. There is deliberately no route
    // that filters them by employee, and nothing written carries an identity.
    const response = await asAdmin().get("/admin/invoices/records");
    expect(JSON.stringify(response.body)).not.toMatch(/employeeId|employeeHash/);
  });
});
